### ISSUE TITLE
jupyter_ascending module not found in python even though installed with pip 

### ISSUE THREAD

**Issue by ochalkley-advai** [imbue-ai/jupyter_ascending#58]
I have always followed the instructions in the README.md and they have always worked for me but suddenly they don't:

    conda activate env_name
    pip install notebook
    pip install jupyter_ascending

All work without error but then when I try:

    $ python -m jupyter nbextension    install jupyter_ascending --sys-prefix --py
    Traceback (most recent call last):
      File "/usr/bin/jupyter-nbextension", line 33, in <module>
        sys.exit(load_entry_point('notebook==6.4.8', 'console_scripts', 'jupyter-nbextension')())
      File "/usr/lib/python3/dist-packages/jupyter_core/application.py", line 264, in launch_instance
        return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
      File "/usr/lib/python3/dist-packages/traitlets/config/application.py", line 846, in launch_instance
        app.start()
      File "/usr/lib/python3/dist-packages/notebook/nbextensions.py", line 980, in start
        super().start()
      File "/usr/lib/python3/dist-packages/jupyter_core/application.py", line 253, in start
        self.subapp.start()
      File "/usr/lib/python3/dist-packages/notebook/nbextensions.py", line 708, in start
        self.install_extensions()
      File "/usr/lib/python3/dist-packages/notebook/nbextensions.py", line 679, in install_extensions
        full_dests = install(self.extra_args[0],
      File "/usr/lib/python3/dist-packages/notebook/nbextensions.py", line 203, in install_nbextension_python
        m, nbexts = _get_nbextension_metadata(module)
      File "/usr/lib/python3/dist-packages/notebook/nbextensions.py", line 1114, in _get_nbextension_metadata
        m = import_item(module)
      File "/usr/lib/python3/dist-packages/traitlets/utils/importstring.py", line 38, in import_item
        return __import__(parts[0])
    ModuleNotFoundError: No module named 'jupyter_ascending'

Any reason why this would have stopped working?

**Comment by WillWang8216** [comment]
I got the same problem.

**Comment by ochalkley-advai** [comment]
Following information from https://stackoverflow.com/questions/76893872/modulenotfounderror-no-module-named-notebook-base-when-installing-nbextension I was able to solve the problem.

`pip install --upgrade notebook==6.4.12`

So it seems that jupyter-ascending is not compatible with the most recent versions of notebook. Is there plans to update this?
